### ISSUE TITLE
How do you make those beautiful presentations? 

### ISSUE THREAD

**Issue by npalladium** [codereport/Content#4]
Not an issue (at least in the traditional sense). 

When I was watching your AccuConf 2021 talk, I was blown away by your slides and more specifically the animations (among other things). 

I was curious about how you do the animations, especially the text ones. 

Could you please briefly talking about the tooling/process? 

Thank you.

**Comment by amarzot** [comment]
@npalladium I had to go down the rabbit hole as well. 

https://twitter.com/code_report/status/1443173554590138370
> Thanks! I do all my presentations in [@Microsoft](https://twitter.com/Microsoft) [@powerpoint](https://twitter.com/powerpoint). I will make a video in the next couple on tips and tricks that I use.


 I don't think there has been a video made yet though.

**Comment by codereport** [comment]
Video explanation finally made: https://www.youtube.com/watch?v=Vh3y1ela-_s
