### ISSUE TITLE
Wrong implementation

### ISSUE THREAD

**Issue by Masynchin** [codereport/Content#5]
Hello, @codereport!

It seems that your python implementation for phi combinator is wrong. Current implementation is:

~~~python
def phi(f, g, h, x):
    return g(f(x), h(x))
~~~

And correct is:

~~~python
def phi(f, g, h, x):
    return f(g(x), h(x))
~~~

Related file: https://github.com/codereport/Content/blob/main/Publications/MSc_Thesis_A_Combinator_NDimenstional_Array_Library_in_Smalltalk.pdf

Section 2.6.9

**Comment by codereport** [comment]
Yes and no. I have gotten this comment a couple times. Although these two are slightly different, I consider them "equivalent". The lambda expression form is for Phi is `λabcd.a(bd)(cd)` but I consider the spelling `λabcd.b(ad)(cd)` "equivalent" in that all that has been rearranged are the functions that are used in the composition. `abc` here are functions and `d` is the argument to the result function form from using the Phi combinator. So if we use upper case `FGH` for functions and `x` for data, you have `F(Gx)(Hx)` and any reordering of the `FGH` I consider "equivalent."
